services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-xperimne}?schema=public
      - AUTH_URL=https://chat.rakitdigital.my.id
    networks:
      - internet-net
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.xperimne.rule=Host(`chat.rakitdigital.my.id`)
      - traefik.http.services.xperimne.loadbalancer.server.port=3030
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-xperimne}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internet-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:

networks:
  internet-net:
    external: true
